### ISSUE TITLE
[BUG] Unable to complete step Azure Registration

### ISSUE THREAD

**Issue by azwildfire** [Azure/aks-hci#94] opened 2021-05-19 01:02 UTC
**Describe the bug**
While going through the AKS setup via WAC, on step 5 Azure Registration, after authenticating successfully recieve this error:
Could not fetch Azure subscriptions

12:57:02 AM
Source
Go to Azure Kubernetes Service.
Type
Error

Message
Could not fetch Azure subscriptions. Error: Cannot read property 'replace' of undefined

**To Reproduce**
1. Go to 'WAC and try to complete AKS extention setup'

**Expected behavior**
Expect registration to be successful. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35748021/118741282-c9cc8000-b802-11eb-880f-06a56f195dab.png)

**Environment (please complete the following information):**
Default from Github Repo

**Additional context**

**Collect log files**
- From a PowerShell Admin window run **Get-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”

**Comment by arfongmsft** [comment] 2021-05-21 18:20
Hi Richard, 

Can you confirm which WAC build you hit this issue on? You can find that info here:
![image](https://user-images.githubusercontent.com/65312460/119181238-2a87d280-ba26-11eb-8658-16940cabb3aa.png)

To get around this issue, you need to have installed the WAC hotfix version that came in the zip download -- it should look like this:
![wachotfixaks](https://user-images.githubusercontent.com/65312460/119181494-881c1f00-ba26-11eb-97e6-54c98aa2b361.png)

Thanks,
Ariel

**Comment by abhilashaagarwala** [comment] 2021-06-07 20:54
Can you try this on the AKS-HCI GA release and let us know if it persists? https://github.com/Azure/aks-hci/releases/tag/AKS-HCI-2105

**Comment by mkostersitz** [comment] 2021-06-16 16:16
@azwildfire  Hello Richard, were you able to verify that the issue is resolved in the GA build? If not please let us know so we can work with you to figure out what is going on

**Comment by madhanrm** [comment] 2021-08-02 17:40
can we close this bug @mkostersitz  ?

**Comment by mkostersitz** [comment] 2021-08-02 17:42
Closing this issue as it has become stale and is not reproducible on our side

**Closed by mkostersitz** 2021-08-02 17:42 UTC
Labels: bug
