### ISSUE TITLE
uninstall-akshci exception caught - unable to locate a valid cloudconfig access file

### ISSUE THREAD

**Issue by DaStivi** [Azure/aks-hci#43] opened 2020-10-06 14:29 UTC
after ah failure attempt to deploy aks on my azure stack hci cluster, i end up now with the message in the wac: "An Azure Kubernetes Service is already setup on this Azure Stack HCI but is not configured correctly. Please clean up your environment to setup again."

but uninstall-akshci only ends up in the error in title... " exception caught - unable to locate a valid cloudconfig access file"

cloudconfig files does simply not exist in the userpath\.wssd\ ...
also creating an empty file does not help do pass the  uninstall wizard, as it looks like the wizard checks the files for validity.. 

so i ended up now with an unfinished interrupted deployment and can't clean up...
i've deleted the created clusterressources manually but looks like that wasn't enough, still wac complains about....

**Comment by nwoodmsft** [comment] 2020-10-26 19:28
We are tracking this to be fixed in the November release.

**Comment by abhilashaagarwala** [comment] 2021-03-17 21:12
@nwoodmsft Can we close this bug if this was fixed in the November release?

**Comment by madhanrm** [comment] 2021-06-07 21:31
Can you please try the latest GA build

**Comment by mkostersitz** [comment] 2021-06-16 16:10
Closing. This does not reproduce in GA. If you find the issue is not fixed, please open a new issue with new logs.

**Closed by mkostersitz** 2021-06-16 16:10 UTC
Labels: bug
