### ISSUE TITLE
[BUG] Update-AksHci stuck on "Waiting for deployment 'AksHci Billing Operator' to be ready..."

### ISSUE THREAD

**Issue by zawachte-msft** [Azure/aks-hci#120] opened 2021-08-17 14:39 UTC
**Describe the bug**

I attempted to update AksHci and was hung the status message "Waiting for deployment 'AksHci Billing Operator' to be ready..."

**To Reproduce**

1. Update-Akshci
2. Wait around an hour or so and see the status message stuck here. 

**Expected behavior**

**Screenshots**

![Screenshot 2021-08-10 101753](https://user-images.githubusercontent.com/45979377/129746366-54f95cdb-f442-48ea-90cc-1dfc56f92ba7.png)

**Comment by zawachte-msft** [comment] 2021-08-17 14:43
This bug can have a couple of root causes. The first possibility is that during the update of the AksHci Billing Operator, the Operator incorrectly marked itself as out of policy. To remedy this just open up another shell and run.

```ps
Sync-AksHciBilling
```

You should see the billing operation continue within the next 20-30 minutes.

**Comment by Elektronenvolt** [comment] 2021-08-17 15:15
I had the same issue as I tried to connect / update to the cluster over Windows Admin Center. No connection because of billing operator not reachable.
Root cause was the same issue as described here: [aks-hci/issues/118](https://github.com/Azure/aks-hci/issues/118#issuecomment-899795043)

Mgmt cluster VM out of memory -> API server not reachable -> all commands from Get-AksHciCluster, billing, update, e.g. run into a timeout. 
My workaround: I've set the mgmt cluster VM to 32GB in Hyper-V and rebooted it. Same story during an AksHci update. A new mgmt cluster VM gets created during the update and I immediately set it to 32GB.

**Comment by zawachte-msft** [comment] 2021-08-17 16:41
Another issue is that the AksHci Billing Operator is out of storage space. This is due to a bug in the mssql configuration settings. This is fixed in future releases and will be fixed on an update to the august or September build.

If this is causing an upgrade to hang, please manually resize the billing pod pvc:

```ps
kubectl edit pvc mssql-data-claim --kubeconfig (Get-AksHciConfig).Kva.kubeconfig -n azure-arc 
```

Notepad or another editor should pop up with a yaml that looks like the following.

```yaml
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: disk.csi.akshci.com
  creationTimestamp: "2021-08-13T17:49:15Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: mssql-data-claim
  namespace: azure-arc
  resourceVersion: "3313301"
  uid: 9b5e4fd0-858c-4549-b295-f7b89a4dd6ce
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: default
  volumeMode: Filesystem
  volumeName: pvc-9b5e4fd0-858c-4549-b295-f7b89a4dd6ce
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  phase: Bound
```
Please edit the line that is in storage from 100Mi to 5Gi

```yaml
spec:
  resources:
    requests:
      **storage: 5Gi**
```

**Comment by madhanrm** [comment] 2021-08-18 06:04
@zawachte-msft - can you file the billing pod space issue as a separate bug ?

**Comment by abhilashaagarwala** [comment] 2021-08-18 23:11
Assigning it to @EkeleAsonye  so we can include it in the AKS-HCI troubleshooting guide(s) - https://docs.microsoft.com/en-us/azure-stack/aks-hci/known-issues

**Closed** 2021-09-09 18:38 UTC
Labels: bug
