### ISSUE TITLE
WAC Set up AKS stuck on Package download

### ISSUE THREAD

**Issue by DaStivi** [Azure/aks-hci#39] opened 2020-09-30 08:52 UTC
WAC is stuck on Package download page, WAC Maschine has full internet connection without any proxy needed, also the hci nodes doesn't need an proxy and can access internet... 

the wizard just counts the duration, but never finishes nor get an error, as it looks like something is blocking  the download apparently because even after almost 2hours of waiting it didn't finish!?

**Comment by dineshgovindasamy** [comment] 2020-09-30 21:21
@mattatmsft

**Comment by DaStivi** [comment] 2020-10-05 16:28
an Update to the root issues of not downloading, or better said, don't do anything at all...
i've installed WAC on another Admin Machine and there  al the host configuration and management cluter creation steps, and the package download process is now correctly shown...

the issue on the other machine was that only for a split second the 3 sections did show up and then vanished, and only the duraction counter stayed...

it looks like that some adblocking add-on maybe caused the issue! i'm not totally sure right now as i'm still in the progress of deploying/downloading, so i won't cross test this now in my primary machine without add-ons... but most propably, if another user reads this, try disabling all (adBlock) plugins!

**Comment by BenjaminArmstrong** [comment] 2020-10-07 21:16
Closing out as this appears to be caused by an add-on

**Closed by BenjaminArmstrong** 2020-10-07 21:16 UTC
